# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180222_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ip_address',
            field=models.GenericIPAddressField(default=''),
            preserve_default=False,
        ),
    ]
